### ISSUE TITLE
OctaPrint/Obico Connected but sending Cancel does not cancel the print.

### ISSUE THREAD

**Issue by ixodides** [jneilliii/OctoPrint-BambuPrinter#86]
I have a setup using Obico for OctoPrint and the Bambu Printer Plugin from [jneilliii](https://github.com/jneilliii). The connection between all components works correctly — I can send print from BambuLab and the printer starts printing as expected. I can see live status updates on Octa and Obico, including bed and nozzle temperatures rising, and the print progress appears in both interfaces.

Problem:
When I try to cancel a print via Obico or OctoPrint, the cancel command appears to be sent — the interfaces briefly indicate the cancel action — but the printer does not actually stop the print. The print continues running on the Bambu printer, and Obico reverts back to showing the job as "Printing".

Expected Behavior:
Cancelling a print from either Obico or OctoPrint should properly stop the print on the Bambu printer.

Environment:

OctoPrint version:  OctoPrint 1.11.2 Python 3.11.2 OctoPi* 1.1.0 (build 2025.06.10.114348)

Obico Plugin version: Obico for OctoPrint (2.5.4)

Bambu Printer Plugin version: Bambu Printer (0.1.7)

Bambu printer model: [e.g., X1C, P1P, etc.] P1S

Let me know if logs or debug output are needed.

**Comment by jneilliii** [comment]
This might be something fixed in the rc version of this plugin. Go into software update settings and set the release channel to release candidate for the Bambu plugin and upgrade when promoted.

**Comment by ixodides** [comment]
Thank you for you message. This time the behavior was slightly different.

On Obico I pressed cancel print and Obico cancelled it and remained cancelled on Obico but print was still happening. 

On OctaPrint the behavior remained same. 

https://drive.google.com/file/d/1_8k-LZY_Jbkm2KYqsCh926xBiwUY_Qbs/view?usp=sharing

Recv: SD printing byte 1/506608
Changing monitoring state from "Printing from SD" to "Cancelling"
Send: N56 M108*25
Recv: ok
Send: N57 M25*38
Recv: ok
Send: N58 M27*43
Recv: SD printing byte 1/506608
Recv: ok
Send: N59 M26 S0*104
Recv: SD printing byte 1/506608
Recv: Done printing file
Changing monitoring state from "Cancelling" to "Finishing"
Recv: Not SD printing
Recv: ok
Send: N60 M84*41
Recv: ok
Send: N61 M104 T0 S0*22
Recv: ok
Send: N62 M140 S0*81
Recv: ok
Send: N63 M106 S0*82
Recv: ok
Changing monitoring state from "Finishing" to "Operational"
Send: N64 M400*21
Recv: ok
Recv: Not SD printing
Recv: T:73.00/ 75.00 B:55.00/ 55.00 @:64
Recv: File opened: szablo~1.3mf Size: 506608
Recv: File selected
Recv: File opened: szablo~1.3mf Size: 506608
Recv: File selected
Recv: SD printing byte 1/506608
Changing monitoring state from "Operational" to "Starting print from SD"
Changing monitoring state from "Starting print from SD" to "Printing from SD"
Recv: SD printing byte 1/506608
Recv: SD printing byte 1/506608

**Comment by jneilliii** [comment]
Go into OctoPrint's logging section and set the level for plugin_bambuprinter to debug and reproduce the issue and then share your octoprint.log and bambuprinter logs that get generated.

**Comment by ixodides** [comment]
Here are the logs 

[plugin_bambu_printer_serial.zip](https://github.com/user-attachments/files/21551776/plugin_bambu_printer_serial.zip)

**Comment by jneilliii** [comment]
> 2025-08-01 18:27:46,015 - octoprint_bambu_printer.printer.pybambu - DEBUG - Sent {'print': {'sequence_id': '0', 'command': 'stop'}} to topic device/01P00C541801536/request
2025-08-01 18:27:46,015 - octoprint.plugins.bambu_printer.BambuPrinter.states - INFO - print cancelled

it very much looks like the command is being sent to the printer to stop. 

one thing I notice, you will want to remove and gcode scripts configured in OctoPrint's settings for sure. 

> 2025-08-01 18:27:46,187 - octoprint_bambu_printer.printer.pybambu - WARNING - HMS ERRORS: {'Count': 1, '1-Code': 'HMS_0500_0500_0001_0007', '1-Error': 'unknown', '1-Wiki': 'https://wiki.bambulab.com/en/x1/troubleshooting/hmscode/0500_0500_0001_0007', '1-Severity': 'fatal'}

doing a little research this may be a newer firmware update lock down, and your printer needs to be in LAN Only + Developer mode. https://forum.bambulab.com/t/error-hms-0500-0500-0001-0007-what-to-do/172631
